extensions:
  health_check:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        # OTLP HTTP receiver endpoint
        endpoint: 0.0.0.0:4318
  zipkin:

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 2G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  debug:
    verbosity: detailed
  file/traces:
    path: /log/otel/traces.log
  file/metrics:
    path: /log/otel/metrics.log
  file/logs:
    path: /log/otel/logs.log
  otlp:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "${PROMETHEUS_ENDPOINT}"
  loki:
    endpoint: "${LOKI_ENDPOINT}"
    tls:
      insecure: true
  zipkin:
    endpoint: "${ZIPKIN_ENDPOINT}"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
        - otlp
        - zipkin
      processors: [memory_limiter, batch]
      exporters:
        - debug 
        - file/traces
        - otlp
        - zipkin
    metrics:
      receivers:
        - otlp
      processors: [memory_limiter, batch]
      exporters:
        - debug 
        - file/metrics
        - prometheus
    logs:
      receivers:
        - otlp
      processors: [memory_limiter, batch]
      exporters:
        - debug 
        - file/logs
        - loki
  extensions:
    - health_check
    - zpages